version: '3.8'
services:
  postgresdb:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_DB=RestApi
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password1!
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/RestApi
  app:
    image: 'restapi-0.0.5:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - postgresdb